services:
  - type: web
    name: robinhood-portfolio-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api_server.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4