services:
  - type: web
    name: robinhood-portfolio-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection false
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: STREAMLIT_SERVER_PORT
        value: 10000
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: false
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false